### PR TITLE
Just testing the branch

### PR DESCRIPTION
**Pull request by tkuennen**

### CODE REVIEW

**Comment by tkuennen** [comment]
Merging the branch with master

**Comment by wiltbemj** [comment]
Did a bit of googling and found this command on stackoverflow

git clone user@git-server:project_name.git -b branch_name --single-branch /some/folder

It creates a folder that is just the branch so you can play with it independent of the master.  I was able to get github desktop to work with this branch by using the + to add the local repository.  

The link to the stackoverflow page is [here](http://stackoverflow.com/questions/1778088/how-to-clone-a-single-branch-in-git)

**Comment by tkuennen** [comment]
I tried this but it cloned an empty folder. Maybe try git clone git@github.com:ncar/mhdpy.git ~/somenewfolder this creates an entire new copy of the repo, and you can just git commit if you like the changes, or delete the folder if you don't like

**Comment by wiltbemj** [comment]
Hi Travis,
  I did a git clone git@github.com:NCAR/MHDpy.git -b change-to-pythonindex MHDpy-pythonindex
to create a new folder.  I can then point the desktop at this folder and all appears to be working.  I’m doing a new development path and will merge the branch back once I complete the new feature.  I added this to a comment on one of your threads in github.

Take care,
Mike

Michael Wiltberger, Ph.D    
NCAR/HAO            
3080 Center Green        
Boulder, CO 80301        
Ph: (303)497-1532        
Fx: (303)497-2180        
email: wiltbemj@ucar.edu    

There are only 10 types of people: those who understand binary and those who don't.

On February 3, 2016 at 4:11:32 PM, Travis Kuennen (notifications@github.com) wrote:

I tried this but it cloned an empty folder. Maybe try git clone git@github.com:ncar/mhdpy.git ~/somenewfolder this creates an entire new copy of the repo, and you can just git commit if you like the changes, or delete the folder if you don't like

**Pull request merged**
